build:
  image: fedora:latest
  script:
    - dnf update -y
    - dnf install -y acl rpm-build dpkg pacman
    - umask 0022
    - setfacl --restore=permissions.facl
    - rpmbuild -ba brace.spec
    - dpkg-deb --build brace
    - awk -i inplace '!/exit \$E_ROOT/' $(which makepkg)
    - makepkg
  artifacts:
    paths:
        - build/noarch/brace*.rpm
        - brace.deb
        - brace*.pkg.tar.*
