image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y acl gawk which fakeroot rpm-build dpkg dpkg-dev pacman
  - umask 0022
  - setfacl --restore=permissions.facl

build_rpm:
  stage: build
  script:
    - rpmbuild -ba brace.spec
  artifacts:
    paths:
        - build/noarch/brace*.rpm

build_deb:
  stage: build
  script:
    - dpkg-deb --root-owner-group --build brace && dpkg-name brace.deb
  artifacts:
    paths:
        - brace*.deb

build_arch:
  stage: build
  script:
    - awk -i inplace '!/exit \$E_ROOT/' $(which makepkg)
    - awk -i inplace '!/lint_package/' $(which makepkg)
    - makepkg
  artifacts:
    paths:
        - brace*.pkg.tar.*
