#!/bin/sh
#Copyright (c) 2018-2024 Divested Computing Group
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ]; then
	echo "Enabling DNF automatic update download/install";
	dnf install dnf-automatic rpm-plugin-systemd-inhibit;
	sed -i 's/apply_updates = no/apply_updates = yes/g' /etc/dnf/automatic.conf;
	if type "dnf5" > /dev/null 2>&1; then
		systemctl enable dnf5-automatic.timer --now;
	else
		systemctl enable dnf-automatic-install.timer --now;
	fi;
	echo "Do you want automatic reboots after installing?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				sed -i 's/reboot = never/reboot = when-changed/g' /etc/dnf/automatic.conf;
				break;;
			No )
				sed -i 's/reboot = when-changed/reboot = never/g' /etc/dnf/automatic.conf;
				break;;
		esac
	done
else
	echo "Currently only Fedora is supported";
fi;
