#!/bin/bash
#Copyright (c) 2015-2020 Divested Computing Group
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

coloroff='\e[0m';
black='\e[0;30m';
blue='\e[0;34m';
cyan='\e[0;36m';
green='\e[0;32m';
purple='\e[0;35m';
red='\e[0;31m';
white='\e[0;37m';
yellow='\e[0;33m';

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo -e "${red}ERROR: This script needs to be run as root!${coloroff}"; exit 1; fi;

#
#Start functions
#
whichPackageManager() {
	if type "zypper" > /dev/null 2>&1; then
		echo "zypper" && return 0;
	fi;
	if type "dnf" > /dev/null 2>&1; then
		echo "dnf" && return 0;
	fi;
	if type "yum" > /dev/null 2>&1; then
		echo "yum" && return 0;
	fi;
	if type "pacman" > /dev/null 2>&1; then
		echo "pacman" && return 0;
	fi;
	if type "apt" > /dev/null 2>&1; then
		echo "apt" && return 0;
	fi;
	#if type "flatpak" > /dev/null 2>&1; then
	#	echo "flatpak" && return 0;
	#fi;
}

handleInstall() {
	if [ "$packageManager" == "apt" ]; then
		packagesCombined="$packagesDebian $packagesBaseDebian";
		#Credit (CC BY-SA 4.0): https://superuser.com/a/1623381
		for packageToCheck in $packagesCombined
		do
			if [ -z "$(apt-cache madison $packageToCheck 2>/dev/null)" ]; then
				echo -e "${yellow}Warning: Skipping missing package: $packageToCheck ${coloroff}";
			else
				packagesToInstallReal="$packagesToInstallReal $packageToCheck";
			fi;
		done
		$packageManager install --no-install-recommends $packagesToInstallReal;
	fi;
	if [ "$packageManager" == "dnf" ] || [ "$packageManager" == "yum" ]; then
		$packageManager install --skip-broken $packagesFedora $packagesBaseFedora && $packageManager mark install --skip-broken $packagesFedora $packagesBaseFedora;
	fi;
	if [ "$packageManager" == "flatpak" ]; then
		$packageManager install $packagesFlathub $packagesBaseFlathub;
	fi;
	if [ "$packageManager" == "pacman" ]; then
		#TODO: handle AUR?
		$packageManager -S --needed $packagesArch $packagesBaseArch;
	fi;
	if [ "$packageManager" == "zypper" ]; then
		$packageManager install $packagesSuse $packagesBaseSuse;
	fi;
}

handleRemove() {
	if [ "$packageManager" == "apt" ]; then
		$packageManager remove $packagesDebian;
	fi;
	if [ "$packageManager" == "dnf" ] || [ "$packageManager" == "yum" ]; then
		$packageManager remove --skip-broken $packagesFedora;
	fi;
	if [ "$packageManager" == "flatpak" ]; then
		$packageManager remove $packagesFlathub;
	fi;
	if [ "$packageManager" == "pacman" ]; then
		#$packageManager -Rsc $packagesArch;
		for package in $packagesArch; do
			$packageManager -Rsc $package;
		done;
	fi;
	if [ "$packageManager" == "zypper" ]; then
		$packageManager remove $packagesSuse;
	fi;
}

cleanupOperation() {
	unset category baseIncluded packagesArch packagesDebian packagesFedora packagesFlathub packagesSuse packagesCombined packageToCheck packagesToInstallReal;
}

handleOperation() {
	if [ "$baseInstall" = true ]; then
		if [ "$baseIncluded" = true ]; then
			echo -e "${green}Including packages from the $category category${coloroff}";
			if [ "$packageManager" == "apt" ]; then
				packagesBaseDebian="$packagesBaseDebian $packagesDebian";
			fi;
			if [ "$packageManager" == "dnf" ] || [ "$packageManager" == "yum" ]; then
				packagesBaseFedora="$packagesBaseFedora $packagesFedora";
			fi;
			if [ "$packageManager" == "flatpak" ]; then
				packagesBaseFlathub="$packagesBaseFlathub $packagesFlathub";
			fi;
			if [ "$packageManager" == "pacman" ]; then
				packagesBaseArch="$packagesBaseArch $packagesArch";
			fi;
			if [ "$packageManager" == "zypper" ]; then
				packagesBaseSuse="$packagesBaseSuse $packagesSuse";
			fi;
		else
			echo -e "${yellow}Skipping packages from the $category category${coloroff}";
		fi;
	else
		echo -e "${purple}Do you want packages from the $category category?${coloroff}";
		select yns in "Yes" "No" "Skip"; do
			case $yns in
				Yes )
					handleInstall;
					break;;
				No )
					handleRemove;
					break;;
				Skip )
					#do nothing
					break;;
			esac;
		done;
	fi;
	cleanupOperation;
}

handleCleanup() {
	if [ "$packageManager" == "apt" ]; then
		$packageManager autoremove;
	fi;
	if [ "$packageManager" == "dnf" ] || [ "$packageManager" == "yum" ]; then
		$packageManager autoremove;
	fi;
	if [ "$packageManager" == "flatpak" ]; then
		$packageManager remove --unused;
	fi;
	if [ "$packageManager" == "pacman" ]; then
		$packageManager -Rns $(pacman -Qttdq);
		paccache -rk0;
	fi;
	if [ "$packageManager" == "zypper" ]; then
		#TODO: handle this, similar to pacman
		true;
	fi;
}
#
#End functions
#

#
#Start glue
#
echo -e "${cyan}INFO: This script is intended for use on desktop machines, not servers!${coloroff}";
echo -e "${cyan}INFO: This script is geared towards personal use and some packages may not be appropiate for business systems!${coloroff}";
if [ -f /etc/centos-release ]; then yum install epel-release; fi;

packageManager=$(whichPackageManager);
if [ -z ${packageManager} ]; then
	echo -e "${red}ERROR: No package manager found!${coloroff}";
	return 1;
else
	echo -e "${cyan}INFO: Using $packageManager as package manager${coloroff}";
fi;

echo -e "${purple}Would you like to simply install all recommended packages?${coloroff}";
select yn in "Yes" "No"; do
	case $yn in
		Yes )
			baseInstall=true;
			break;;
		No )
			baseInstall=false;
			break;;
	esac;
done;
#
#End glue
#

#
#Start categories
#
category='Recommended for Removal';
	baseIncluded=false;
	packagesArch='gnome-documents gnome-weather gnome-music gnome-software packagekit epiphany sushi';
	packagesDebian='gnome-documents gnome-weather gnome-music gnome-games rhythmbox gnome-software packagekit sushi';
	packagesFedora='abiword adapta-gtk-theme akregator amarok asunder calligra* clipit clipman compiz emerald empathy exaile falkon filezilla geany gnomebaker gnome-documents gnome-weather gnote gnumeric hexchat juk k3b kget kmahjongg kmines konqueror konversation kpatience ktnef ktorrent lxmusic midori osmo paper-icon-theme pidgin *powerline pragha qlipper quassel qupzilla rhythmbox xawtv xfburn xfdashboard xpad yarock gnome-software PackageKit dnfdragora* sushi passim';
	packagesSuse='gnome-documents gnome-weather gnome-music brasero iagno lightsoff gnome-mahjongg pidgin polari tigervnc swell-foop xterm sushi';
	handleOperation;
category='Core';
	baseIncluded=true;
	packagesArch='rng-tools irqbalance openssh nano htop wget screen zip p7zip pixz pigz lm_sensors ripgrep dialog crda pacman-contrib lostfiles'; packagesAUR='downgrade';
	packagesDebian='rng-tools irqbalance ssh nano htop wget screen p7zip pixz lm-sensors ripgrep unattended-upgrades';
	packagesFedora='rng-tools irqbalance openssh nano htop wget screen p7zip pixz lm_sensors ripgrep grubby';
	packagesSuse='rng-tools irqbalance openssh nano htop wget screen p7zip pixz sensors ripgrep grubby';
	handleOperation;
category='Frameworks';
	baseIncluded=false;
	packagesArch='jre8-openjdk python';
	packagesDebian='default-jre';
	packagesFedora='java-1.8.0-openjdk';
	packagesSuse='java-1_8_0-openjdk';
	handleOperation;
category='GNOME Extras';
	baseIncluded=false;
	packagesArch='gnome-tweak-tool file-roller gedit';
	packagesDebian='nautilus-extension-gnome-terminal gnome-tweak-tool file-roller gedit';
	packagesFedora='gnome-terminal-nautilus gnome-tweak-tool file-roller gedit';
	packagesSuse='nautilus-terminal gnome-tweaks file-roller gedit';
	handleOperation;
category='OpenCL';
	baseIncluded=false;
	packagesArch='';
	packagesDebian='clinfo mesa-opencl-icd pocl-opencl-icd';
	packagesFedora='clinfo mesa-libOpenCL pocl';
	packagesSuse='clinfo Mesa-libOpenCL pocl';
	handleOperation;
category='VA-API';
	baseIncluded=true;
	packagesArch='libva-mesa-driver libva-utils libva-intel-driver intel-media-driver gstreamer-vaapi';
	packagesDebian='mesa-va-drivers vainfo i965-va-driver intel-media-va-driver gstreamer1.0-vaapi';
	packagesFedora='mesa-dri-drivers mesa-va-drivers libva libva-utils libva-intel-driver libva-intel-hybrid-driver'; #gstreamer1-vaapi (https://bugzilla.redhat.com/show_bug.cgi?id=2129000)
	packagesSuse=''; #TODO
	handleOperation;
category='VDPAU';
	baseIncluded=false;
	packagesArch='vdpauinfo libvdpau libvdpau-va-gl libva-vdpau-driver mesa-vdpau';
	packagesDebian='vdpauinfo libvdpau-va-gl1 vdpau-va-driver';
	packagesFedora='vdpauinfo libvdpau libvdpau-va-gl libva-vdpau-driver';
	packagesSuse=''; #TODO
	handleOperation;
category='Theming';
	baseIncluded=true;
	packagesArch=''; packagesAUR='numix-circle-icon-theme-git';
	packagesDebian='numix-icon-theme-circle';
	packagesFedora='numix-icon-theme-circle';
	packagesSuse='';
	handleOperation;
category='Fonts';
	baseIncluded=true;
	packagesArch='adobe-source-code-pro-fonts ttf-fira-mono ttf-fira-sans ttf-liberation cantarell-fonts gsfonts noto-fonts noto-fonts-emoji';
	packagesDebian='';
	packagesFedora='adobe-source-code-pro-fonts mozilla-fira-mono-fonts mozilla-fira-sans-fonts';
	packagesSuse='adobe-sourcecodepro-fonts';
	handleOperation;
category='Audio Manipulation';
	baseIncluded=true;
	packagesArch='audacity';
	packagesDebian='audacity';
	packagesFedora='audacity';
	packagesFlathub='org.audacityteam.Audacity';
	packagesSuse='audacity';
	handleOperation;
category='Chat';
	baseIncluded=true;
	packagesArch='hexchat dino mumble';
	packagesDebian='hexchat dino-im mumble';
	packagesFedora='hexchat dino mumble';
	packagesFlathub='io.github.Hexchat info.mumble.Mumble';
	packagesSuse='hexchat gajim gajim-plugin-omemo mumble';
	handleOperation;
category='Communication';
	baseIncluded=true;
	packagesArch='evolution';
	packagesDebian='evolution';
	packagesFedora='evolution';
	packagesFlathub='org.gnome.Evolution';
	packagesSuse='evolution';
	handleOperation;
category='Development';
	baseIncluded=false;
	packagesArch='git gitg ghex sqlitebrowser gcc';
	packagesDebian='git gitg ghex sqlitebrowser build-essential';
	packagesFedora='git gitg ghex sqlitebrowser @development-tools';
	packagesFlathub='org.gnome.gitg org.gnome.GHex';
	packagesSuse='git gitg ghex sqlitebrowser'; #devel_basis
	handleOperation;
category='Development - Android';
	baseIncluded=false;
	packagesArch='android-udev android-tools enjarify'; packagesAUR='android-apktool sdat2img android-studio';
	packagesDebian='adb fastboot enjarify';
	packagesFedora='android-tools enjarify';
	packagesSuse=''; #unavailable
	handleOperation;
category='Development - Java';
	baseIncluded=false;
	packagesArch='jdk8-openjdk'; packagesAUR='proguard jd-gui launch4j';
	packagesDebian='default-jdk proguard';
	packagesFedora='java-1.8.0-openjdk-devel eclipse-jdt proguard';
	packagesSuse=''; #unavailable
	handleOperation;
category='Development - Distro Specific Packaging';
	baseIncluded=false;
	packagesArch='asp';
	packagesDebian='';
	packagesFedora='rpmbuild fedpkg';
	packagesSuse='rpmbuild';
	handleOperation;
category='Disks - Management';
	baseIncluded=true;
	packagesArch='testdisk smartmontools parted';
	packagesDebian='testdisk smartmontools parted';
	packagesFedora='testdisk smartmontools parted';
	packagesSuse='testdisk smartmontools parted';
	handleOperation;
category='Disks - File Systems';
	baseIncluded=true;
	packagesArch='btrfs-progs compsize dosfstools exfat-utils f2fs-tools mtools ntfs-3g udftools xfsprogs duperemove sshfs';
	packagesDebian='btrfs-progs btrfs-compsize dosfstools exfat-utils f2fs-tools mtools ntfs-3g udftools xfsprogs duperemove sshfs';
	packagesFedora='btrfs-progs compsize dosfstools exfat-utils f2fs-tools mtools ntfs-3g ntfsprogs udftools xfsprogs duperemove fuse-sshfs';
	packagesSuse='btrfsprogs compsize dosfstools exfat-utils f2fs-tools mtools ntfs-3g ntfsprogs udftools xfsprogs duperemove sshfs';
	handleOperation;
category='Files - Backup';
	baseIncluded=true;
	packagesArch='restic';
	packagesDebian='restic';
	packagesFedora='restic';
	packagesSuse='restic';
	handleOperation;
category='Files - Encryption';
	baseIncluded=true;
	packagesArch='gocryptfs';
	packagesDebian='gocryptfs';
	packagesFedora='gocryptfs cryptsetup-reencrypt';
	packagesSuse=''; #unavailable
	handleOperation;
category='Files - Sharing';
	baseIncluded=true;
	packagesArch='transmission-gtk';
	packagesDebian='transmission-gtk';
	packagesFedora='transmission';
	packagesFlathub='com.transmissionbt.Transmission';
	packagesSuse='transmission-gtk';
	handleOperation;
category='Files - Syncing';
	baseIncluded=false;
	packagesArch='syncthing';
	packagesDebian='syncthing';
	packagesFedora='syncthing';
	packagesSuse='syncthing';
	handleOperation;
category='Games - Tiny';
	baseIncluded=false;
	packagesArch='quadrapassel gnome-mines gnome-chess gnome-sudoku aisleriot';
	packagesDebian='quadrapassel gnome-mines gnome-chess gnome-sudoku aisleriot';
	packagesFedora='quadrapassel gnome-mines gnome-chess gnome-sudoku aisleriot nethack-vultures';
	packagesSuse='quadrapassel gnome-mines gnome-chess gnome-sudoku aisleriot';
	handleOperation;
category='Games - Sandbox';
	baseIncluded=false;
	packagesArch='minetest';
	packagesDebian='minetest';
	packagesFedora='minetest';
	packagesSuse='minetest';
	handleOperation;
category='Games - Arena';
	baseIncluded=false;
	packagesArch='xonotic';
	packagesDebian=''; #unavailable
	packagesFedora='xonotic';
	packagesSuse='xonotic';
	handleOperation;
category='Image Manipulation - CLI';
	baseIncluded=true;
	packagesArch='imagemagick jpegoptim optipng';
	packagesDebian='imagemagick jpegoptim optipng';
	packagesFedora='ImageMagick jpegoptim optipng';
	packagesSuse='ImageMagick jpegoptim optipng';
	handleOperation;
category='Image Manipulation - Graphical';
	baseIncluded=true;
	packagesArch='gimp inkscape darktable pitivi';
	packagesDebian='gimp inkscape darktable pitivi';
	packagesFedora='gimp gimpfx-foundry inkscape darktable pitivi';
	packagesSuse='gimp inkscape darktable pitivi';
	handleOperation;
category='Internet';
	baseIncluded=true;
	packagesArch='firefox firefox-ublock-origin chromium liferea';
	packagesDebian='firefox-esr chromium chromium-sandbox liferea';
	packagesFedora='firefox mozilla-ublock-origin chromium liferea';
	packagesSuse='MozillaFirefox chromium liferea';
	handleOperation;
category='Media - Consumption';
	baseIncluded=true;
	packagesArch='ffmpeg vlc lollypop yt-dlp'; #TODO: codecs
	packagesDebian='ffmpeg vlc lollypop youtube-dl'; #TODO: codecs
	packagesFedora='@multimedia ffmpeg gstreamer1-plugin-openh264 vlc lollypop yt-dlp';
	packagesSuse='ffmpeg vlc lollypop yt-dlp'; #TODO: codecs
	handleOperation;
category='Media - Books';
	baseIncluded=false;
	packagesArch='foliate';
	packagesDebian=''; #unavailable
	packagesFedora='foliate';
	packagesSuse='foliate';
	handleOperation;
category='Media - HTPC';
	baseIncluded=false;
	packagesArch='kodi';
	packagesDebian='kodi';
	packagesFedora='kodi';
	packagesSuse=''; #unavailable
	handleOperation;
category='Media - Music Management';
	baseIncluded=false;
	packagesArch='picard soundconverter sound-juicer';
	packagesDebian='picard soundconverter sound-juicer';
	packagesFedora='picard soundconverter sound-juicer';
	packagesSuse='picard soundconverter sound-juicer';
	handleOperation;
category='Office';
	baseIncluded=true;
	packagesArch='libreoffice-fresh meld scribus gnucash aspell aspell-en hyphen hyphen-en libmythes mythes-en qalculate-gtk';
	packagesDebian='libreoffice meld scribus gnucash dia aspell aspell-en qalculate-gtk';
	packagesFedora='libreoffice libreoffice-writer libreoffice-calc libreoffice-impress libreoffice-draw libreoffice-base meld scribus gnucash dia aspell aspell-en qalculate-gtk';
	packagesSuse='libreoffice meld scribus gnucash dia aspell';
	handleOperation;
category='Passwords';
	baseIncluded=true;
	packagesArch='keepassxc pwgen'; packagesAUR='u2f-hidraw-policy';
	packagesDebian='keepassxc pwgen diceware ssss libu2f-udev';
	packagesFedora='keepassxc pwgen diceware ssss u2f-hidraw-policy';
	packagesSuse='keepassxc pwgen libu2f-host0';
	handleOperation;
category='Privacy';
	baseIncluded=true;
	packagesArch='bleachbit'; packagesAUR='scrub';
	packagesDebian='bleachbit scrub';
	packagesFedora='bleachbit srm scrub';
	packagesSuse='bleachbit srm scrub';
	handleOperation;
category='Reference';
	baseIncluded=false;
	packagesArch='kiwix-desktop';
	packagesDebian=''; #unavailable
	packagesFedora='kiwix-desktop';
	packagesSuse=''; #unavailable
	handleOperation;
category='Screencast';
	baseIncluded=false;
	packagesArch='obs-studio';
	packagesDebian='obs-studio';
	packagesFedora='obs-studio';
	packagesSuse=''; #unavailable
	handleOperation;
category='Security - Malware Scanner';
	baseIncluded=false;
	packagesArch='clamav clamtk';
	packagesDebian='clamav clamtk';
	packagesFedora='clamav clamav-data-empty clamav-update clamtk';
	packagesSuse='clamav clamtk';
	handleOperation;
category='Security - System';
	baseIncluded=true;
	packagesArch='firewalld firejail apparmor linux-hardened';
	packagesDebian='firewalld firewall-config firejail firejail-profiles apparmor apparmor-profiles apparmor-profiles-extra apparmor-utils';
	packagesFedora='firewalld firewall-config firejail';
	packagesSuse='firewalld firewall-config firejail apparmor-profiles';
	handleOperation;
category='Tor';
	baseIncluded=true;
	packagesArch='tor torsocks onionshare torbrowser-launcher';
	packagesDebian='tor torsocks onionshare'; #torbrowser-launcher (contrib)
	packagesFedora='tor torsocks onionshare torbrowser-launcher';
	packagesSuse='tor torsocks python3-onionshare torbrowser-launcher'; #torbrowser-apparmor-profile
	handleOperation;
category='Utility';
	baseIncluded=true;
	packagesArch='whois mtr stress iotop wavemon pv tree iperf3 bmon powertop ncdu intel-gpu-tools radeontop fwupd';
	packagesDebian='dconf-cli whois mtr stress iotop wavemon pv tree iperf3 bmon powertop ncdu vrms intel-gpu-tools radeontop fwupd';
	packagesFedora='whois mtr stress iotop wavemon pv tree iperf3 bmon powertop ncdu vrms-rpm intel-gpu-tools radeontop fwupd';
	packagesSuse='whois mtr stress-ng iotop wavemon pv tree iperf bmon powertop ncdu intel-gpu-tools radeontop';
	handleOperation;
category='Utility - Graphical';
	baseIncluded=true;
	packagesArch='dconf-editor gnome-firmware gsmartcontrol seahorse';
	packagesDebian='dconf-editor gnome-firmware software-properties-gtk gsmartcontrol seahorse';
	packagesFedora='dconf-editor gnome-firmware gsmartcontrol seahorse openssh-askpass';
	packagesFlathub='org.gnome.seahorse.Application';
	packagesSuse='dconf-editor gsmartcontrol seahorse';
	handleOperation;
category='Virtualization';
	baseIncluded=false;
	packagesArch='libvirt virt-manager qemu';
	packagesDebian=''; #TODO
	packagesFedora='@virtualization';
	packagesSuse=''; #'Install Hypervisor' can be used
	handleOperation;
#
#End categories
#

#Queued base install if selected
if [ "$baseInstall" = true ]; then
	handleInstall;
	echo -e "${cyan}INFO: Packages installed${coloroff}";
fi;

#Cleanup
echo -e "${cyan}INFO: Cleaning up${coloroff}";
handleCleanup;

#Finish
echo -e "${cyan}INFO: Installer complete!${coloroff}";
