#!/bin/sh
#Copyright (c) 2018-2020 Divested Computing Group
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ]; then
	if [ -z "$1" ]; then echo 'You must provide a version to upgrade to'; exit 1; fi;
	if rpm -qi hardened_malloc > /dev/null; then echo "Please disable or uninstall hardened_malloc before starting the system update."; fi;

	dnf distro-sync --refresh;
	dnf install dnf-plugin-system-upgrade;
	dnf system-upgrade download --refresh --releasever="$1";
else
	echo "Currently only Fedora is supported";
fi;
