#!/bin/sh
#Copyright (c) 2018-2020 Divested Computing Group
#License: GPLv3

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ]; then
	echo "Enabling DNF automatic update download/install";
	dnf install dnf-automatic;
	systemctl enable dnf-automatic-install.timer --now;
else
	echo "Currently only Fedora is supported";
fi;
