#!/bin/sh
#Copyright (c) 2018-2020 Divested Computing Group
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <https:#www.gnu.org/licenses/>.

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ] || [ -f /etc/centos-release ]; then
	echo "Enabling RPM Fusion Free";
	echo "Please verify the RPM Fusion signing keys from here: https://rpmfusion.org/keys";
	echo "F33-39 E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E";
	echo "EL8: 8379 35CD 19E1 23AA 7F8A  8E69 979F 0C69 158B 3811";
	echo "EL7: DB9A 9A57 CAFD 23DA 3A88  792F 758B 3D18 F5CF 6C1E";
fi;

if [ -f /etc/fedora-release ]; then
	dnf install "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm";
elif [ -f /etc/centos-release ]; then
	yum install epel-release;
	yum localinstall --nogpgcheck "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %centos).noarch.rpm";
else
	echo "Currently only Fedora and CentOS are supported";
fi;
